# Generated by Django 6.0.3 on 2026-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('tappetino', 'Tappetini'), ('telo_bagno', 'Telo bagno'), ('telo_viso', 'Telo viso'), ('telo_bidet', 'Telo bidet'), ('lenzuolo_matrimoniale', 'Lenzuolo matrimoniale'), ('lenzuolo_singolo', 'Lenzuolo singolo'), ('copripiumino_matrimoniale', 'Copripiumino matrimoniale'), ('copripiumino_singolo', 'Copripiumino singolo'), ('federa', 'Federe')], max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(choices=[('tappetino', 'Tappetini'), ('telo_bagno', 'Telo bagno'), ('telo_viso', 'Telo viso'), ('telo_bidet', 'Telo bidet'), ('lenzuolo_matrimoniale', 'Lenzuolo matrimoniale'), ('lenzuolo_singolo', 'Lenzuolo singolo'), ('copripiumino_matrimoniale', 'Copripiumino matrimoniale'), ('copripiumino_singolo', 'Copripiumino singolo'), ('federa', 'Federe')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('dirty', 'Sporco'), ('clean', 'Pulito')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
