# Generated by Django 6.0.3 on 2026-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrymovement',
            name='movement_type',
            field=models.CharField(choices=[('dirty', 'Sporco'), ('clean', 'Pulito'), ('add', 'Integrazione'), ('remove', 'Diminuzione')], max_length=10),
        ),
    ]
