# Generated by Django 6.0.3 on 2026-03-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_alter_laundrymovement_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='laundryinventory',
            options={'ordering': ['item']},
        ),
        migrations.AlterModelOptions(
            name='laundrymovement',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='laundryinventory',
            name='item',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='laundrymovement',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
