# Generated by Django 6.0.3 on 2026-07-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cleanings", "0009_cleaningconsumption"),
        ("employees", "0002_employee_user"),
        ("laundry", "0003_laundryitem_alter_laundryinventory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laundrymovement",
            name="cleaning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laundry_movements",
                to="cleanings.cleaning",
                verbose_name="Pulizia collegata",
            ),
        ),
        migrations.AddField(
            model_name="laundrymovement",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laundry_movements",
                to="employees.employee",
                verbose_name="Dipendente",
            ),
        ),
    ]
