# Generated by Django 6.0.3 on 2026-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città/Zona')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Proprietario')),
                ('average_cleaning_time', models.PositiveIntegerField(default=2, verbose_name='Tempo medio pulizia (ore)')),
                ('access_notes', models.TextField(blank=True, verbose_name='Note accesso')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Note interne')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appartamento',
                'verbose_name_plural': 'Appartamenti',
                'ordering': ['name'],
            },
        ),
    ]
