# Generated by Django 6.0.3 on 2026-03-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='access_notes',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='average_cleaning_time',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='double_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='operational_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='single_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='square_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
