# Generated by Django 6.0.3 on 2026-03-09 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['name'], 'verbose_name': 'Immobile', 'verbose_name_plural': 'Immobili'},
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='square_meters',
        ),
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('condo', 'Condominio'), ('office', 'Ufficio'), ('shop', 'Locale'), ('other', 'Altro')], default='house', max_length=20, verbose_name='Tipo immobile'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Codice'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
