# Generated by Django 6.0.3 on 2026-03-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_apartment_options_remove_apartment_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='default_cleaning_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo pulizia'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_fixed_kit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo kit fisso'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_laundry_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo biancheria'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_per_person_kit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo kit a persona'),
        ),
    ]
