# Generated by Django 6.0.3 on 2026-03-17 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_default_cleaning_cost_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='customers.customer', verbose_name='Cliente'),
        ),
    ]
