# Generated by Django 6.0.3 on 2026-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='default_laundry_cost',
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_double_bed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo letto matrimoniale'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_mat_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tappetino'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='default_single_bed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo letto singolo'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='double_beds',
            field=models.IntegerField(default=0, verbose_name='Letti matrimoniali totali'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='single_beds',
            field=models.IntegerField(default=0, verbose_name='Letti singoli totali'),
        ),
    ]
