# Generated by Django 6.0.3 on 2026-05-03 21:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_apartmentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Foto'),
        ),
    ]
