# Generated by Django 6.0.3 on 2026-03-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('note_type', models.CharField(choices=[('PROP', 'Prop'), ('CANE', 'Cane'), ('SOLO_PULIZIA', 'Solo pulizia'), ('NO_BIANCHERIA', 'No biancheria'), ('TUTTI_LETTI', 'Tutti i letti')], max_length=30, verbose_name='Tipo nota')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Nota aggiuntiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_notes', to='apartments.apartment', verbose_name='Appartamento')),
            ],
            options={
                'verbose_name': 'Nota giornaliera',
                'verbose_name_plural': 'Note giornaliere',
                'ordering': ['date'],
                'unique_together': {('apartment', 'date', 'note_type')},
            },
        ),
    ]
