# Generated by Django 6.0.3 on 2026-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynote',
            name='note_type',
            field=models.CharField(choices=[('PROP', 'Prop'), ('CANE', 'Cane'), ('SOLO_PULIZIA', 'Solo pulizia'), ('NO_BIANCHERIA', 'No biancheria'), ('TUTTI_LETTI', 'Tutti i letti'), ('CUSTOM', 'Nota libera'), ('VISIBLE', 'Nota visibile')], max_length=30, verbose_name='Tipo nota'),
        ),
    ]
