# Generated by Django 6.0.3 on 2026-03-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('bookings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data pulizia')),
                ('status', models.CharField(choices=[('scheduled', 'Programmato'), ('in_progress', 'In corso'), ('completed', 'Completato')], default='scheduled', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='apartments.apartment', verbose_name='Appartamento')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanings', to='bookings.booking', verbose_name='Prenotazione collegata')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanings', to='employees.employee', verbose_name='Dipendente assegnato')),
            ],
            options={
                'verbose_name': 'Pulizia',
                'verbose_name_plural': 'Pulizie',
                'ordering': ['date'],
            },
        ),
    ]
