# Generated by Django 6.0.3 on 2026-03-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='employee',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='cleanings', to='employees.employee', verbose_name='Dipendenti assegnati'),
        ),
    ]
