# Generated by Django 6.0.3 on 2026-03-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0002_remove_cleaning_employee_cleaning_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='employee_note',
            field=models.TextField(blank=True, verbose_name='Nota finale dipendente'),
        ),
    ]
