# Generated by Django 6.0.3 on 2026-03-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_default_cleaning_cost_and_more'),
        ('cleanings', '0003_cleaning_employee_note'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cleaning',
            name='notes',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='cleaning_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo pulizia'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='extra_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='fixed_kit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo kit fisso'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='laundry_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo biancheria'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='per_person_kit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo kit a persona'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='apartments.apartment', verbose_name='Immobile'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='cleanings', to='employees.employee', verbose_name='Dipendenti'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmato'), ('completed', 'Completato')], default='scheduled', max_length=20, verbose_name='Stato'),
        ),
    ]
