# Generated by Django 6.0.3 on 2026-03-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_booking_double_beds_and_more'),
        ('cleanings', '0004_remove_cleaning_booking_remove_cleaning_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='auto_created',
            field=models.BooleanField(default=False, verbose_name='Creata automaticamente'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleanings', to='bookings.booking', verbose_name='Prenotazione collegata'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='manual_date_override',
            field=models.BooleanField(default=False, verbose_name='Data modificata manualmente'),
        ),
    ]
