# Generated by Django 6.0.3 on 2026-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0005_cleaning_auto_created_cleaning_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='laundry_cost',
        ),
        migrations.AddField(
            model_name='cleaning',
            name='double_bed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo letto matrimoniale'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='double_beds_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti matrimoniali utilizzati'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='mat_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tappetino'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='people_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero persone'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='single_bed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo letto singolo'),
        ),
        migrations.AddField(
            model_name='cleaning',
            name='single_beds_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti singoli utilizzati'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='cleaning_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo pulizia'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='fixed_kit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo kit fisso'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='per_person_kit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo kit a persona'),
        ),
    ]
