# Generated by Django 6.0.3 on 2026-03-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0006_remove_cleaning_laundry_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cleaning_attachments/', verbose_name='File')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Caricato il')),
                ('cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cleanings.cleaning', verbose_name='Pulizia')),
            ],
            options={
                'verbose_name': 'Allegato pulizia',
                'verbose_name_plural': 'Allegati pulizia',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
