# Generated by Django 6.0.3 on 2026-03-29 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0007_cleaningattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningattachment',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='File'),
        ),
    ]
