# Generated by Django 6.0.3 on 2026-06-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanings', '0008_alter_cleaningattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cleaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='cleanings.cleaning')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
