# Generated by Django 6.0.3 on 2026-03-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome cliente')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='Ragione sociale')),
                ('vat_number', models.CharField(blank=True, max_length=30, verbose_name='Partita IVA')),
                ('tax_code', models.CharField(blank=True, max_length=30, verbose_name='Codice fiscale')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['name'],
            },
        ),
    ]
