# Generated by Django 6.0.3 on 2026-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_hours', '0002_alter_worklog_options_worklog_expenses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlyrate',
            options={'ordering': ['employee', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['date', 'employee_id']},
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='extra_personnel',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='km',
        ),
        migrations.AlterField(
            model_name='hourlyrate',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
