# Generated by Django 6.0.3 on 2026-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beds_double',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti matrimoniali da preparare'),
        ),
        migrations.AddField(
            model_name='booking',
            name='beds_single',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti singoli da preparare'),
        ),
    ]
