# Generated by Django 6.0.3 on 2026-03-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_beds_double_booking_beds_single'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='beds_double',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='beds_single',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guests_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='source',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
