# Generated by Django 6.0.3 on 2026-03-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_remove_booking_beds_double_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in'], 'verbose_name': 'Prenotazione', 'verbose_name_plural': 'Prenotazioni'},
        ),
        migrations.AddField(
            model_name='booking',
            name='double_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti matrimoniali'),
        ),
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero persone'),
        ),
        migrations.AddField(
            model_name='booking',
            name='single_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti singoli'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome ospite'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
