# Generated by Django 6.0.3 on 2026-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_booking_double_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='double_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti matrimoniali utilizzati'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='single_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Letti singoli utilizzati'),
        ),
    ]
