# Generated by Django 6.0.3 on 2026-03-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0003_alter_apartment_options_remove_apartment_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondominiumCleaningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data fine')),
                ('frequency', models.CharField(choices=[('daily', 'Giornaliera'), ('twice_week', '2 volte settimana'), ('weekly', 'Settimanale'), ('biweekly', 'Quindicinale'), ('monthly', 'Mensile')], max_length=20, verbose_name='Frequenza')),
                ('preferred_day_1', models.IntegerField(blank=True, choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], null=True, verbose_name='Giorno preferito 1')),
                ('preferred_day_2', models.IntegerField(blank=True, choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], null=True, verbose_name='Giorno preferito 2')),
                ('work_hours', models.FloatField(verbose_name='Ore lavoro (1 persona)')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_rules', to='apartments.apartment', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'Regola pulizia condominio',
                'verbose_name_plural': 'Regole pulizia condomini',
                'ordering': ['apartment', 'start_date'],
            },
        ),
    ]
